### ISSUE TITLE
请问运行报错file = sys.argv[1]  IndexError: list index out of range该如何解决？谢谢

### ISSUE THREAD

**Issue by vermontleo** [hit-computer/char-rnn-tf#11]
2017-08-28 18:15:11,067 INFO - Traceback (most recent call last):
2017-08-28 18:15:11,067 INFO - File "train.py", line 14, in <module>
2017-08-28 18:15:11,067 INFO - file = sys.argv[1]
2017-08-28 18:15:11,067 INFO - IndexError: list index out of range
这是我在floydhub上测试的结果
我尝试着修改了file的路径，但是不理想，不知道问题出在了哪里？
请问您有头绪么？
谢谢

**Comment by vermontleo** [comment]
我将数据直接与.py文件放在一个文件夹内，并修改data引用为
with open('nlgtest.txt', 'r') as f:
	data = f.read()
这个样可以调用数据了
然后，新的问题。。。
2017-08-28 20:15:17,076 INFO - _run_using_default_session(self, feed_dict, self.graph, session)
2017-08-28 20:15:17,076 INFO - File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3764, in _run_using_default_session
2017-08-28 20:15:17,076 INFO - session.run(operation, feed_dict)
2017-08-28 20:15:17,076 INFO - File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 767, in run
2017-08-28 20:15:17,087 INFO - run_metadata_ptr)
2017-08-28 20:15:17,088 INFO - File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 965, in _run
2017-08-28 20:15:17,088 INFO - feed_dict_string, options, run_metadata)
2017-08-28 20:15:17,088 INFO - File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1015, in _do_run
2017-08-28 20:15:17,088 INFO - target_list, options, run_metadata)
2017-08-28 20:15:17,088 INFO - File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1035, in _do_call
2017-08-28 20:15:17,088 INFO - raise type(e)(node_def, op, message)
2017-08-28 20:15:17,117 INFO - tensorflow.python.framework.errors_impl.ResourceExhaustedError: <exception str() failed>
2017-08-28 20:15:18,840 INFO - 
################################################################################
2017-08-28 20:15:18,840 INFO - Waiting for container to complete...
2017-08-28 20:15:19,221 INFO - [failed] Task execution failed in 176 seconds for TaskInstance <TaskInstance: zarathustra/projects/quick-start/7 (id: KUXnJ9UQb2PwwgxJetGET8)
2017-08-28 20:15:19,343 INFO - Docker container exited with status code: 1
我晕了

**Comment by vermontleo** [comment]
哦，我自己找到了，原来是GPU使用的问题，在train.py中加入如下代码即可
config_tf.gpu_options.allocator_type ='BFC'
config_tf.gpu_options.per_process_gpu_memory_fraction = 0.80
这样看来，这个问题可以关闭了
