### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero 问题？

### ISSUE THREAD

**Issue by RuojiRuoli** [hit-computer/char-rnn-tf#9]
你好呀，我也在搞中文文本生成，不过刚刚才学习，资料太少了，好不容易才看见你的这个。

我想问下我运行程序的时候会出现下面的错误：
2017-07-01 22:39:07.199671: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0)
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.BasicLSTMCell object at 0x7ff6cc713350>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
Training Epoch: 1 ...
Traceback (most recent call last):
  File "train.py", line 98, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "train.py", line 89, in main
    train_perplexity = run_epoch(session, m, train_data, m.train_op)
  File "train.py", line 66, in run_epoch
    if step and step % (epoch_size // 10) == 0:
ZeroDivisionError: integer division or modulo by zero

这个是为什么呢？咋会出现这个错误啊？

**Comment by hit-computer** [comment]
@RuojiRuoli 这里主要是你的数据量比较小，导致计算得到的运行轮数epoch_size小于10，从而epoch_size // 10结果为0。其实这段代码的意思时，每次迭代输出10次信息，你可以把这里的10改成1，甚至注释掉这里的输出控制。

**Comment by syssys** [comment]
数据量小的缘故

**Comment by syssys** [comment]
@hit-computer 我也在研究这一块，可以加个微信或QQ交流一些想法吗？

**Comment by RuojiRuoli** [comment]
@hit-computer 谢谢，果然跑通了。:)
慢慢看代码，路还好长。

**Comment by RuojiRuoli** [comment]
@syssys 谢谢，确实是这个问题。:)
